import math
import warnings

import torch
import torch.nn as nn


@torch.no_grad()
def trunc_normal_(tensor, mean=0.0, std=1.0, a=-2.0, b=2.0):
    # Method based on https://people.sc.fsu.edu/~jburkardt/presentations/truncated_normal.pdf
    def norm_cdf(x):
        # Computes standard normal cumulative distribution function
        return (1.0 + math.erf(x / math.sqrt(2.0))) / 2.0

    if (mean < a - 2 * std) or (mean > b + 2 * std):
        warnings.warn(
            "mean is more than 2 std from [a, b] in nn.init.trunc_normal_. "
            "The distribution of values may be incorrect.",
            stacklevel=2,
        )

    # Values are generated by using a truncated uniform distribution and
    # then using the inverse CDF for the normal distribution.
    # Get upper and lower cdf values
    lower = norm_cdf((a - mean) / std)
    upper = norm_cdf((b - mean) / std)

    # Uniformly fill tensor with values from [l, u], then translate to
    # [2l-1, 2u-1].
    tensor.uniform_(2 * lower - 1, 2 * upper - 1)

    # Use inverse cdf transform for normal distribution to get truncated
    # standard normal
    tensor.erfinv_()

    # Transform to proper mean, std
    tensor.mul_(std * math.sqrt(2.0))
    tensor.add_(mean)

    # Clamp to ensure it's in the proper range
    tensor.clamp_(min=a, max=b)
    return tensor


def modify_channelvit_input_channels(model, new_in_chans):
    """
    Modify a pre-trained ChannelVIT model to accept a different number of input channels.

    Args:
        model: Pre-trained ChannelVIT model
        new_in_chans: New number of input channels

    Returns:
        Modified model
    """
    is_hcs = "hcs_channel_vit" in model.__class__.__module__

    # Store original number of channels
    original_in_chans = model.in_chans

    if new_in_chans == original_in_chans:
        return model

    # 1. Update the model's in_chans attribute
    model.in_chans = new_in_chans

    # 2. Create a new channel embedding with the new number of channels
    old_channel_embed = model.patch_embed.channel_embed
    if is_hcs:
        new_channel_embed = nn.Embedding(new_in_chans, model.embed_dim)
    else:
        new_channel_embed = nn.parameter.Parameter(
            torch.zeros(1, model.embed_dim, new_in_chans, 1, 1)
        )

    # Initialize the new channel embedding
    with torch.no_grad():
        # Copy weights for the original channels
        if original_in_chans <= new_in_chans:
            if is_hcs:
                new_channel_embed.weight[:original_in_chans, :] = (
                    old_channel_embed.weight
                )
            else:
                new_channel_embed[:, :, :original_in_chans, :, :] = old_channel_embed
        else:
            if is_hcs:
                new_channel_embed.weight = old_channel_embed.weight[:new_in_chans, :]
            else:
                new_channel_embed = old_channel_embed[:, :, :new_in_chans, :, :]

        # Initialize the new channels with the mean of existing channels
        if new_in_chans > original_in_chans:
            if is_hcs:
                mean_embed = old_channel_embed.weight.mean(dim=0, keepdim=True)
                for i in range(original_in_chans, new_in_chans):
                    new_channel_embed.weight[i, :] = mean_embed
            else:
                mean_embed = old_channel_embed.mean(dim=2, keepdim=True)
                for i in range(original_in_chans, new_in_chans):
                    new_channel_embed[:, :, i : i + 1, :, :] = mean_embed

    # Apply truncated normal initialization to maintain consistency
    # with the model's initialization
    if new_in_chans > original_in_chans:
        if is_hcs:
            trunc_normal_(new_channel_embed.weight[original_in_chans:, :], std=0.02)
        else:
            trunc_normal_(new_channel_embed[:, :, original_in_chans:, :, :], std=0.02)

    # Replace the channel embedding
    model.patch_embed.channel_embed = new_channel_embed

    # 3. Update the position embedding to account for the new number of channels
    # This is crucial since the pos_embed assumes a specific number of channels
    num_patches_per_channel = model.pos_embed.shape[1] - 1  # Subtract 1 for cls token
    num_patches = num_patches_per_channel * new_in_chans
    model.patch_embed.num_patches = num_patches

    # No need to modify pos_embed here as the model's interpolate_pos_encoding
    # method already handles different input sizes and channel counts

    return model
